---
title: "Introduction"
description: |
  Dear reader, welcome to my blog
author:
  - name: François Fokan
    url: {}
date: 04-09-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Here you will find a whole series of ***scientific article reviews concerning the behaviour of primates***. But that's not all !

You can also find the different sections down there:

-	**About Me**
That’s right, who is François Fokan?

-	**About Primates**
It seems important to start at the beginning.

-	**My English Activity Log (M.E.A.L.)**
All about my progress in English.

-	**Graphic Description**
A collaboration with the SDD course.

-	**Introduction, Conclusion & Bibliography**

Why did I decide to deal with this topic ? Being a biology student, it was obvious that I was going to choose a topic treating of biology. I've always been very interested in zoology and in particular ethology, the study of animal behavior. So the Primate Behavior topic was perfect. 

The purpose of this blog is to introduce you to primates in more depth and try to convey my passion for this subject to you. After reading these analysis, if you want to learn more, my mission will be accomplished.

Each analysis is accompanied by a **vocabulary table** where complicated terms from the original article are explained.

I recommend the "***About Me***" section to find out everything about my background and my motivations.

Good reading !

Francois.
